### PR TITLE
Refactor: Added new Executive Members 23-24' and moved former Executive Members to Ex-Executive Members

### PR DESCRIPTION
**Pull request by vrn21**

### CODE REVIEW

**Comment by jaison080** [comment]
Is accordion for 2021-2022 present?

**Comment by jaison080** [comment]
Also can you convert all the team members image from jpeg to webp.It basically should increase the performance of website.

**Comment by vrn21** [comment]
twice accordion item 20-21 was called, changed that to 20-21 and 21-22.

converted and compressed jpegs of executive team 23-24 to webp

**Comment by jaison080** [comment]
Awesome work 👏👏

**Review by jaison080 — APPROVED** [review]
Awesome work 👏👏

**Pull request merged**
