### PR TITLE
Feat: Added a new announcements section and more

### PR DESCRIPTION
**Pull request by subru-37**
Style: Fixed font-size of pre-incubation page, Fix: Fixed redirecting of links making it open in next page

### CODE REVIEW

**Comment by aldrinjenson** [comment]
Hey @subru-37 , great work! 

Few minor suggestions:
- please add a bit more padding for the card. If the card is too small, then feel free to increase the width
image

Also, for the first announcement, please cut down the description a bit and remove the link in description as it's already present in the Instagram post. 
Thanks!

**Comment by subru-37** [comment]
So the summary for the first Announcement card:

"It is a common notion that fields such as economics or finance are too complicated for us to understand, an effort to simplify these topics and help you explore the same, IEDC MEC presents "InSights" . A reel series where we will breakdown tricky concepts starting from economics to business, finance and technology.

For more details visit:
https://www.instagram.com/p/CjIm0FKvrYQ/"

Is this enough?
Or shall I cut down last sentence too, then it will be like the amount of content 2nd Announcement card will have

**Comment by aldrinjenson** [comment]
Hey, I think this could do for now:

IEDCMEC presents a reel series where we breakdown tricky concepts starting from economics to business, finance and technology.

For more details visit:
https://www.instagram.com/p/CjIm0FKvrYQ/"

**Comment by subru-37** [comment]
How is the latest commit?

**Comment by aldrinjenson** [comment]
Looks good!

@joeljosh , please take a look at the code and merge this when free

**Pull request merged**
